package bookmgr.UI;

import bookmgr.exceptions.BookDoesntExistException;
import bookmgr.exceptions.UserDoesntExistException;
import bookmgr.main.Connection;
import bookmgr.repos.AdminRepo;
import java.util.ArrayList;

/**
 * View for printing a report on all loans
 */
public class RentReportView extends javax.swing.JFrame {

    public RentReportView() {
        initComponents();
        ErrorBox.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GetButton = new javax.swing.JButton();
        ErrorBox = new javax.swing.JLabel();
        CurrentBox = new javax.swing.JCheckBox();
        ReturnedBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("bookMGR - Report");
        setResizable(false);

        GetButton.setText("Get");
        GetButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        GetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetButtonActionPerformed(evt);
            }
        });

        ErrorBox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ErrorBox.setEnabled(false);

        CurrentBox.setText("Current loans");

        ReturnedBox.setText("Returned");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ErrorBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ReturnedBox, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CurrentBox))
                        .addGap(0, 84, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(GetButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(CurrentBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReturnedBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GetButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ErrorBox, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void GetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetButtonActionPerformed
        Connection conn = new Connection();
        AdminRepo newRepo = new AdminRepo();
        if (CurrentBox.isSelected() && ReturnedBox.isSelected()) {
            try {
                ArrayList<String> list = newRepo.reportForAllRents(2);
                ReportView newView = new ReportView(list);
                newView.render();
            } catch (BookDoesntExistException | UserDoesntExistException ex) {
                ErrorBox.setText("A report could not be formed.");
                ErrorBox.setVisible(true);
            }
        } else if (CurrentBox.isSelected()) {
            try {
                ArrayList<String> list = newRepo.reportForAllRents(0);
                ReportView newView = new ReportView(list);
                newView.render();
            } catch (BookDoesntExistException | UserDoesntExistException ex) {
                ErrorBox.setText("A report could not be formed.");
                ErrorBox.setVisible(true);
            }
        } else if (ReturnedBox.isSelected()) {
            try {
                ArrayList<String> list = newRepo.reportForAllRents(1);
                ReportView newView = new ReportView(list);
                newView.render();
            } catch (BookDoesntExistException | UserDoesntExistException ex) {
                ErrorBox.setText("A report could not be formed.");
                ErrorBox.setVisible(true);
            }
        } else {
            ErrorBox.setText("Please select what to form reports on.");
            ErrorBox.setVisible(true);
        }
        conn.close();
    }//GEN-LAST:event_GetButtonActionPerformed

    public void render() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentReportView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentReportView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentReportView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentReportView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RentReportView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CurrentBox;
    private javax.swing.JLabel ErrorBox;
    private javax.swing.JButton GetButton;
    private javax.swing.JCheckBox ReturnedBox;
    // End of variables declaration//GEN-END:variables
}
